
server.port=8093


spring.data.mongodb.uri=mongodb://localhost:27017/fitness-recommendation
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}


gemini.api.url=${GEMINI-API-URL}
gemini.api.key=${GEMINI-API-KEY}