spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config
server.port=8094

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
